let products = [
  {id:1, name:'실크 블라우스', price:39000, emoji:'👚', tag:'LIVE 특가', detail:'가볍고 부드러운 소재의 데일리 블라우스입니다.'},
  {id:2, name:'클래식 토트백', price:52000, emoji:'👜', tag:'재고 8개', detail:'수납이 넉넉한 깔끔한 디자인의 토트백입니다.'},
  {id:3, name:'골드 진주 귀걸이', price:18000, emoji:'✨', tag:'오늘만', detail:'은은한 진주 포인트로 어디에나 잘 어울립니다.'}
];
function syncOptionFields(){for(const [toggle,group,inputs]of [['enableSize','sizeOptionFields',['sizeOptions']],['enableColor','colorOptionFields',['colorOptions']],['allowCustomOption','customOptionFields',['customOptionLabel','customOptionValues']]]){const enabled=document.getElementById(toggle).checked;document.getElementById(group).hidden=!enabled;for(const id of inputs){document.getElementById(id).required=enabled;document.getElementById(id).disabled=!enabled;}}}
for(const id of ['enableSize','enableColor','allowCustomOption'])document.getElementById(id).addEventListener('change',syncOptionFields);
const storageKey='live-shop-products-v1';
const todaySeoul=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul'}).format(new Date());
const validSaleDate=value=>/^\d{4}-\d{2}-\d{2}$/.test(value)&&!Number.isNaN(Date.parse(value))&&new Date(value).toISOString().slice(0,10)===value;
const requestedDate=new URL(location.href).searchParams.get('date');
let activeSaleDate=validSaleDate(requestedDate||'')?requestedDate:todaySeoul;
let salePages={};
try{const stored=JSON.parse(sellerStorage.getItem('live-shop-sale-pages-v1'));if(stored&&typeof stored==='object'&&!Array.isArray(stored))salePages=stored;}catch{}
function isOnSaleDate(p){return p.visible&&(Array.isArray(salePages[activeSaleDate])?salePages[activeSaleDate].includes(p.id):activeSaleDate===todaySeoul);}
try {const saved=JSON.parse(sellerStorage.getItem(storageKey));if(Array.isArray(saved))products=saved;}catch{}
products=products.map(p=>({...p,stock:p.stock??8,visible:p.visible??true,photos:p.photos??[]}));
const escapeHTML=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let cart=[]; const won=n=>`₩${n.toLocaleString('ko-KR')}`;
const productsEl=document.querySelector('#products'),cartEl=document.querySelector('#cart');
function drawProducts(){productsEl.innerHTML=products.filter(isOnSaleDate).map(p=>`<article class="product"><button class="photo detail-button" onclick="showDetail(${p.id})" aria-label="${escapeHTML(p.name)} 상세 보기">${p.photos.length?`<img src="${escapeHTML(p.photos[0])}" alt="${escapeHTML(p.name)}" />`:p.emoji||'📷'}</button><div class="product-body"><span class="tag">${p.stock>0?(p.hideStock?'':`재고 ${p.stock}개`):'품절'}</span><h3>${escapeHTML(p.name)}</h3><p class="price">${won(p.price)}</p><button onclick="add(${p.id})" ${p.stock===0?'disabled':''}>담기</button></div></article>`).join('')||'<p>등록된 판매 상품이 없습니다.</p>'}
function drawCart(){const total=cart.reduce((s,x)=>s+x.price,0); document.querySelector('#total').textContent=won(total);document.querySelector('#cartCount').textContent=`${cart.length}개`;cartEl.className=`cart ${cart.length?'':'empty'}`;cartEl.innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-row"><span>${escapeHTML(x.name)}</span><span>${won(x.price)} <button onclick="removeItem(${i})">삭제</button></span></div>`).join(''):'상품을 담아주세요.'}
window.add=id=>{const p=products.find(x=>x.id===id);if(!p||!isOnSaleDate(p))return;if(cart.filter(x=>x.id===id).length>=p.stock){alert('선택 가능한 재고 수량을 초과했습니다.');return;}cart.push(p);drawCart();document.querySelector('#order').scrollIntoView({behavior:'smooth'})};window.removeItem=i=>{cart.splice(i,1);drawCart()};
document.querySelector('#copyAccount').onclick=async()=>{await navigator.clipboard.writeText('12345678901234');const b=document.querySelector('#copyAccount');b.textContent='복사되었습니다';setTimeout(()=>b.textContent='계좌번호 복사',1800)};
document.querySelector('#orderForm').onchange=e=>{document.querySelector('#transferBox').style.display=document.querySelector('[value=transfer]').checked?'block':'none'};
document.querySelector('#orderForm').onsubmit=e=>{e.preventDefault();if(!cart.length){alert('상품을 먼저 담아주세요.');return}const data=new FormData(e.target), payment=data.get('payment')==='transfer'?'무통장입금 (입금대기)':'카드결제 (테스트)';document.querySelector('#successText').textContent=`판매일 ${activeSaleDate} · ${payment} 주문입니다. 실제 연결 시 판매일과 주문시각이 Google 스프레드시트에 함께 저장됩니다.`;document.querySelector('#success').showModal()};
document.querySelector('.close-success').onclick=()=>document.querySelector('#success').close();drawProducts();drawCart();
const select=document.querySelector('#productSelect'), productForm=document.querySelector('#productForm');
let draftPhotos=[],photoBusy=false;
const message=text=>document.querySelector('#adminMessage').textContent=text;
function refreshSelect(id=''){select.innerHTML='<option value="">새 상품 등록</option>'+products.map(p=>`<option value="${p.id}">${escapeHTML(p.name)}${p.visible?'':' (숨김)'}</option>`).join('');select.value=String(id);}
function renderPhotos(){const root=document.querySelector('#photoPreviews');root.replaceChildren();draftPhotos.forEach((src,index)=>{const box=document.createElement('div'),img=document.createElement('img'),button=document.createElement('button');img.src=src;img.alt=`상품 사진 ${index+1}`;button.type='button';button.textContent=index===0?'대표 사진 삭제':'사진 삭제';button.onclick=()=>{draftPhotos.splice(index,1);renderPhotos()};box.append(img,button);root.append(box)})}
function loadEditor(){const p=products.find(p=>String(p.id)===select.value);productForm.reset();document.querySelector('#productName').value=p?.name||'';document.querySelector('#productPrice').value=p?.price??'';document.querySelector('#productStock').value=p?.stock??1;document.querySelector('#productDescription').value=p?.detail||'';document.querySelector('#productVisible').checked=p?.visible??true;document.querySelector('#hideProductStock').checked=p?.hideStock??false;document.querySelector('#sizeOptions').value=(p?.sizes||[]).join(', ');document.querySelector('#colorOptions').value=(p?.colors||[]).join(', ');document.querySelector('#allowCustomOption').checked=p?.allowCustomOption??false;document.querySelector('#customOptionLabel').value=p?.customOptionLabel||'';document.querySelector('#enableSize').checked=!!p?.sizes?.length;document.querySelector('#enableColor').checked=!!p?.colors?.length;document.querySelector('#customOptionValues').value=(p?.customOptions||[]).join(', ');syncOptionFields();draftPhotos=[...(p?.photos||[])];renderPhotos();message('');}
select.onchange=loadEditor;
document.querySelector('#productName').addEventListener('input',e=>{if(select.value===''){select.options[0].textContent=e.target.value.trim()?`새 상품: ${e.target.value.trim()}`:'새 상품 등록';}});
select.addEventListener('change',()=>{select.options[0].textContent='새 상품 등록';});
document.querySelector('#adminToggle').onclick=()=>{const panel=document.querySelector('#adminPanel');panel.hidden=!panel.hidden;document.querySelector('#adminToggle').setAttribute('aria-expanded',String(!panel.hidden));if(!panel.hidden)panel.scrollIntoView({behavior:'smooth'})};
async function resizePhoto(file){if(!file.type.startsWith('image/'))throw Error('이미지 파일을 선택해 주세요.');if(file.size>30*1024*1024)throw Error('사진 한 장은 30MB 이하로 선택해 주세요.');const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();const scale=Math.min(1,1000/Math.max(img.naturalWidth,img.naturalHeight));const canvas=document.createElement('canvas');canvas.width=Math.round(img.naturalWidth*scale);canvas.height=Math.round(img.naturalHeight*scale);const ctx=canvas.getContext('2d');ctx.fillStyle='#ffffff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',0.78);}catch{throw Error('사진을 읽을 수 없습니다. JPG 또는 PNG 사진으로 다시 선택해 주세요.');}finally{URL.revokeObjectURL(url)}}
document.querySelector('#productPhotos').onchange=async e=>{const files=[...e.target.files];if(!files.length)return;if(files.length+draftPhotos.length>8){message('상품당 사진은 최대 8장까지 등록할 수 있습니다.');e.target.value='';return;}photoBusy=true;select.disabled=true;document.querySelector('#saveProduct').disabled=true;message('사진을 준비하고 있습니다…');try{const added=[];for(const file of files)added.push(await resizePhoto(file));draftPhotos.push(...added);renderPhotos();message('사진을 선택했습니다. 상품 저장을 눌러 반영하세요.');}catch(error){message(error.message)}finally{photoBusy=false;select.disabled=false;document.querySelector('#saveProduct').disabled=false;e.target.value='';}};
productForm.onsubmit=async e=>{e.preventDefault();if(photoBusy||(typeof catalogBusy!=='undefined'&&catalogBusy))return;const name=document.querySelector('#productName').value.trim();if(!name){message('상품명을 입력해 주세요.');return;}const id=select.value?Number(select.value):Date.now();const old=products.find(p=>p.id===id);const parseOptions=id=>[...new Set(document.querySelector(id).value.split(',').map(s=>s.trim()).filter(Boolean))];const product={id,name,sizes:document.querySelector('#enableSize').checked?parseOptions('#sizeOptions'):[],colors:document.querySelector('#enableColor').checked?parseOptions('#colorOptions'):[],customOptions:document.querySelector('#allowCustomOption').checked?parseOptions('#customOptionValues'):[],allowCustomOption:document.querySelector('#allowCustomOption').checked,customOptionLabel:document.querySelector('#customOptionLabel').value.trim(),hideStock:document.querySelector('#hideProductStock').checked,price:Number(document.querySelector('#productPrice').value),stock:Number(document.querySelector('#productStock').value),detail:document.querySelector('#productDescription').value.trim(),visible:document.querySelector('#productVisible').checked,photos:[...draftPhotos],emoji:old?.emoji||'📷'};const next=old?products.map(p=>p.id===id?product:p):[...products,product];const priorProducts=sellerStorage.getItem(storageKey);const dateIds=salePages[activeSaleDate]||(activeSaleDate===todaySeoul?products.map(p=>p.id):[]);const nextPages={...salePages,[activeSaleDate]:[...new Set([...dateIds,id])]};try{sellerStorage.setItem(storageKey,JSON.stringify(next));try{sellerStorage.setItem('live-shop-sale-pages-v1',JSON.stringify(nextPages));}catch(error){if(priorProducts===null)sellerStorage.removeItem(storageKey);else sellerStorage.setItem(storageKey,priorProducts);throw error;}}catch{message('저장 공간이 부족하거나 브라우저 저장이 차단되었습니다. 사진 수를 줄이거나 브라우저 설정을 확인해 주세요. 변경 내용은 저장되지 않았습니다.');return;}products=next;salePages=nextPages;const counts={};cart=cart.map(p=>{const updated=products.find(x=>x.id===p.id);return updated?{...updated,optionText:p.optionText}:null;}).filter(p=>p?.visible&&(counts[p.id]=(counts[p.id]||0)+1)<=p.stock);drawProducts();drawCart();refreshSelect(id);renderSaleEditor();refreshSavedSalePages();message('상품을 이 브라우저에 저장했습니다.');if(typeof publishSavedProduct==='function')await publishSavedProduct();};
window.showDetail=id=>{const p=products.find(p=>p.id===id);if(!p)return;const root=document.querySelector('#detail');root.className='detail';root.replaceChildren();const title=document.createElement('h2'),description=document.createElement('p'),price=document.createElement('strong');title.textContent=p.name;description.textContent=p.detail;price.textContent=won(p.price);root.append(title,price,description);for(const src of p.photos){const img=document.createElement('img');img.src=src;img.alt=p.name;root.append(img)}document.querySelector('#detailDialog').showModal()};
document.querySelector('#detailDialog .close').onclick=()=>document.querySelector('#detailDialog').close();
refreshSelect();loadEditor();
function renderSaleEditor(){document.querySelector('#saleDate').value=activeSaleDate;document.querySelector('#saleDateHeading').textContent=`${activeSaleDate} 판매 상품`;const url=new URL(location.href);url.searchParams.set('date',activeSaleDate);document.querySelector('#saleLink').value=url.href;}
renderSaleEditor();
const sheetKey='live-shop-sheet-settings-v1';
const sheetStatus=document.querySelector('#sheetStatus');
try{const settings=JSON.parse(sellerStorage.getItem(sheetKey));if(settings){document.querySelector('#sheetUrl').value=settings.sheetUrl||'';document.querySelector('#scriptUrl').value=settings.scriptUrl||'';sheetStatus.textContent='주소 저장됨 · 자동 동기화 미연결';}}catch{}
document.querySelector('#sheetConnect').onclick=()=>{const panel=document.querySelector('#sheetSettings');panel.hidden=!panel.hidden;document.querySelector('#sheetConnect').setAttribute('aria-expanded',String(!panel.hidden));if(!panel.hidden)document.querySelector('#sheetUrl').focus();};
document.querySelector('#sheetForm').onsubmit=e=>{e.preventDefault();const sheetUrl=document.querySelector('#sheetUrl').value.trim(),scriptUrl=document.querySelector('#scriptUrl').value.trim();try{const sheet=new URL(sheetUrl);if(sheet.protocol!=='https:'||sheet.hostname!=='docs.google.com'||!/^\/spreadsheets\/d\/[a-zA-Z0-9_-]+(?:\/|$)/.test(sheet.pathname))throw Error('Google 스프레드시트 주소를 확인해 주세요.');if(scriptUrl){const script=new URL(scriptUrl);if(script.protocol!=='https:'||script.hostname!=='script.google.com'||!/^\/macros\/s\/[a-zA-Z0-9_-]+\/exec$/.test(script.pathname))throw Error('배포된 Apps Script 웹 앱 주소(/exec)를 입력해 주세요.');}sellerStorage.setItem(sheetKey,JSON.stringify({sheetUrl,scriptUrl}));sheetStatus.textContent='주소를 이 브라우저에 저장했습니다. 실제 상품·주문 동기화는 아직 연결되지 않았습니다.';}catch(error){sheetStatus.textContent=error.name==='QuotaExceededError'?'브라우저 저장 공간이 부족합니다.':error.message;}};
