export function showApprovals(login){
 const panel=document.createElement('details');panel.style.cssText='margin:20px auto;padding:20px;max-width:900px;background:white;border:1px solid #ddd;border-radius:12px';
 panel.id='sellerApprovalPanel';
 const heading=document.createElement('summary');heading.textContent='판매자 승인 관리';const refresh=document.createElement('button');refresh.textContent='승인 목록 새로고침';const status=document.createElement('p'),list=document.createElement('div');panel.append(heading,refresh,status,list);document.body.prepend(panel);
 const labels={pending:'승인 대기',approved:'승인됨',rejected:'거절됨',suspended:'이용 중지'};
 async function action(path,data){const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':login.csrf},body:JSON.stringify(data||{})});const value=await response.json();if(!response.ok)throw Error(value.error||'요청에 실패했습니다.');return value;}
 async function load(){refresh.disabled=true;status.textContent='불러오는 중…';try{const result=await action('/api/approvals/list');list.replaceChildren();status.textContent=result.sellers.length?'판매자를 확인한 후 승인해 주세요.':'승인 요청이 없습니다.';for(const seller of result.sellers){const row=document.createElement('section');row.style.cssText='padding:12px 0;border-bottom:1px solid #ddd';const text=document.createElement('p');text.textContent=seller.email+' · '+(labels[seller.status]||seller.status);row.append(text);for(const [value,label]of [['approved','승인'],['rejected','거절'],['suspended','이용 중지']]){const button=document.createElement('button');button.textContent=label;button.disabled=seller.status===value;button.onclick=async()=>{if(!confirm(seller.email+' 계정을 '+label+'하시겠습니까?'))return;button.disabled=true;try{await action('/api/approvals/update',{id:seller.id,status:value});await load();}catch(error){status.textContent=error.message;button.disabled=false;}};row.append(button);}list.append(row);}}catch(error){status.textContent=error.message;}finally{refresh.disabled=false;}}
 refresh.onclick=load;panel.addEventListener('toggle',()=>{if(panel.open)load();});
}
